---
# vars file for tomcat
pkg1: tomcat8
pkg2: tomcat8-admin
state1: present
state2: restarted
cache1: yes
cache2: no
file1: tomcat-users.xml
dest1: /etc/tomcat8
port1: 9090
port2: 8080
path1: /etc/tomcat8/server.xml
server1: http://172.31.36.35:8080
server2: http://172.31.38.18:8080
