---
- hosts: webserver
  tasks:
    - name: user creation
      user:
              name: "{{a}}"
              password: "{{b}}"
              home: "{{c}}"
              uid: "{{d}}"
              shell: "{{e}}"
