---
- hosts: webserver
  tasks:
          - name: installling ngins container
            docker_container:
                    image: nginx
                    name: "nginx{{item}}"
            with_sequence: count=10       
